---
AWSTemplateFormatVersion: "2010-09-09"
Description: Entry point for all stacks

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yml

  SudoBot:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sudobot/main.yml
      Parameters:
        IGWId: !GetAtt VPC.Outputs.IGW
        NACLId: !GetAtt VPC.Outputs.NACL
        VPCId: !GetAtt VPC.Outputs.VPC
        SecurityGroupId: !GetAtt VPC.Outputs.WebSG
