---
AWSTemplateFormatVersion: "2010-09-09"
Description: Elastic IP for brazil VPN

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: brazil-eip

Outputs:
  EIPAllocationId:
    Value: !GetAtt EIP.AllocationId

  EIPAddress:
    Value: !Ref EIP
