---
AWSTemplateFormatVersion: "2010-09-09"
Description: Template for standing up minecraft server

Resources:
  Storage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        BlockPublicAcls: true
      BucketName: sudoservers-minecraft
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: minecraft-storage

Outputs:
  StorageArn:
    Value: !GetAtt Storage.Arn
